language: node_js
node_js:
  - 10
  - 12
branches:
  only:
    - master
    - develop
cache:
  directories:
    - node_modules

before_script:
  - yarn add git+https://github.com/zenryan/lesgo-framework.git#${TRAVIS_BRANCH}

script:
  - yarn coveralls
