#
# https://docs.travis-ci.com/user/deployment-v2/providers/lambda/
#
language: node_js
os: linux
node_js:
  - 12
branches:
  only:
    - master
    - develop
cache:
  directories:
   - node_modules

jobs:
  include:
    - stage: test
      before_script:
        - yarn add git+https://github.com/zenryan/lesgo-lite.git#${TRAVIS_BRANCH}

      script:
        - yarn coveralls